"""Added optional root position id to cash ledger

Revision ID: 2b3017cd9ab2
Revises: 531efd803266
Create Date: 2025-07-24 16:52:41.509098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3017cd9ab2'
down_revision: Union[str, Sequence[str], None] = '531efd803266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_ledger', sa.Column('root_position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cash_ledger', 'positions', ['root_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cash_ledger', type_='foreignkey')
    op.drop_column('cash_ledger', 'root_position_id')
    # ### end Alembic commands ###
