"""Added position model and table

Revision ID: 4b7638ca1cf0
Revises: b2183381cd82
Create Date: 2025-07-17 13:39:25.242131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7638ca1cf0'
down_revision: Union[str, Sequence[str], None] = 'b2183381cd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('open_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realised_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
