"""positions table root_position_id optional for now

Revision ID: 531efd803266
Revises: fc14a6d6f837
Create Date: 2025-07-24 16:37:02.308633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531efd803266'
down_revision: Union[str, Sequence[str], None] = 'fc14a6d6f837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'root_position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'root_position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
