"""Better position model

Revision ID: 55005eab3e94
Revises: 4b7638ca1cf0
Create Date: 2025-07-17 14:01:31.839051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55005eab3e94'
down_revision: Union[str, Sequence[str], None] = '4b7638ca1cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('initial_quantity', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('positions', sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('positions', sa.Column('entry_date', sa.DateTime(), nullable=False))
    op.add_column('positions', sa.Column('average_entry_price', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('positions', sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True))
    op.drop_column('positions', 'average_price')
    op.drop_column('positions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('average_price', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))
    op.drop_column('positions', 'exit_price')
    op.drop_column('positions', 'average_entry_price')
    op.drop_column('positions', 'entry_date')
    op.drop_column('positions', 'entry_price')
    op.drop_column('positions', 'initial_quantity')
    # ### end Alembic commands ###
