"""cash_ledger optional conv. amount and fx rate

Revision ID: 77e698fa79d0
Revises: b70f58be3e9e
Create Date: 2025-07-23 20:40:10.889450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e698fa79d0'
down_revision: Union[str, Sequence[str], None] = 'b70f58be3e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_ledger', 'converted_amount',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.alter_column('cash_ledger', 'fx_at_time_of_conversion',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_ledger', 'fx_at_time_of_conversion',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False)
    op.alter_column('cash_ledger', 'converted_amount',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    # ### end Alembic commands ###
