"""Added currency to cash_ledger

Revision ID: 900a5f60f689
Revises: 98c0520221ba
Create Date: 2025-07-22 17:54:48.329550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900a5f60f689'
down_revision: Union[str, Sequence[str], None] = '98c0520221ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_ledger', sa.Column('currency', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_ledger', 'currency')
    # ### end Alembic commands ###
