"""Added cashflowledger

Revision ID: 98c0520221ba
Revises: 29df9cebe163
Create Date: 2025-07-22 17:17:56.503867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c0520221ba'
down_revision: Union[str, Sequence[str], None] = '29df9cebe163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('flow_type', sa.String(length=100), nullable=False),
    sa.Column('flow_description', sa.String(length=1024), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_ledger_id'), 'cash_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_cash_ledger_portfolio_id'), 'cash_ledger', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_ledger_portfolio_id'), table_name='cash_ledger')
    op.drop_index(op.f('ix_cash_ledger_id'), table_name='cash_ledger')
    op.drop_table('cash_ledger')
    # ### end Alembic commands ###
