"""Added lots model

Revision ID: b2183381cd82
Revises: 6451e15e7340
Create Date: 2025-07-17 00:51:41.227984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2183381cd82'
down_revision: Union[str, Sequence[str], None] = '6451e15e7340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=6), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notional', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=False),
    sa.Column('open_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    op.alter_column('trades', 'currency',
               existing_type=postgresql.ENUM('GBP', 'EUR', 'USD', name='currencyenum'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('trades', 'direction',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='tradetypeenum'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'direction',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('BUY', 'SELL', name='tradetypeenum'),
               existing_nullable=False)
    op.alter_column('trades', 'currency',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('GBP', 'EUR', 'USD', name='currencyenum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
