"""cash_ledger change converted_currency to converted_amount

Revision ID: b70f58be3e9e
Revises: ef029d9e8b78
Create Date: 2025-07-23 13:36:31.570084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70f58be3e9e'
down_revision: Union[str, Sequence[str], None] = 'ef029d9e8b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_ledger', sa.Column('converted_amount', sa.Numeric(precision=18, scale=6), nullable=False))
    op.drop_column('cash_ledger', 'converted_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_ledger', sa.Column('converted_currency', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))
    op.drop_column('cash_ledger', 'converted_amount')
    # ### end Alembic commands ###
