"""Added fx at time of conversion+converted amount to cash_ledger

Revision ID: ef029d9e8b78
Revises: 900a5f60f689
Create Date: 2025-07-23 12:44:37.253785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef029d9e8b78'
down_revision: Union[str, Sequence[str], None] = '900a5f60f689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_ledger', sa.Column('converted_currency', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('cash_ledger', sa.Column('fx_at_time_of_conversion', sa.Numeric(precision=10, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_ledger', 'fx_at_time_of_conversion')
    op.drop_column('cash_ledger', 'converted_currency')
    # ### end Alembic commands ###
