"""Added root_position_id to positions table

Revision ID: fc14a6d6f837
Revises: 77e698fa79d0
Create Date: 2025-07-24 16:35:27.187602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc14a6d6f837'
down_revision: Union[str, Sequence[str], None] = '77e698fa79d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('root_position_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_positions_root_position_id'), 'positions', ['root_position_id'], unique=False)
    op.create_foreign_key(None, 'positions', 'positions', ['root_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_positions_root_position_id'), table_name='positions')
    op.drop_column('positions', 'root_position_id')
    # ### end Alembic commands ###
