permissions = {
    "developer":{
        "can_manage_user":True,
        "can_delete_user":True,
        "can_search_user":True,
        "can_init_portfolio":True,
        "can_manage_portfolio":True,
        "all_permissions":True
    },
    "director":{
        "can_manage_user":True,
        "can_delete_user":False,
        "can_search_user":True,
        "can_init_portfolio":True,
        "can_manage_portfolio":True
    },
    "vd":{
        "can_manage_user":True,
        "can_delete_user":False,
        "can_search_user":True,
        "can_init_portfolio":True,
        "can_manage_portfolio":True
    },
    "pm":{
        "can_manage_user":False,
        "can_delete_user":False,
        "can_search_user":True,
        "can_init_portfolio":False,
        "can_manage_portfolio":True
    },
    "senioranalyst":{
        "can_manage_user":False,
        "can_delete_user":False,
        "can_search_user":False,
        "can_init_portfolio":False,
        "can_manage_portfolio":False
    },
    "analyst":{
        "can_manage_user":False,
        "can_delete_user":False,
        "can_search_user":False,
        "can_init_portfolio":False,
        "can_manage_portfolio":False
    }
}